
# ========================= pyproject.toml (minimal) ==========================
# [build-system]
# requires = ["setuptools", "wheel"]
# build-backend = "setuptools.build_meta"
#
# [project]
# name = "ai-workflows-api"
# version = "0.1.0"
# requires-python = ">=3.11"
# dependencies = [
# "fastapi>=0.115",
# "uvicorn[standard]",
# "pydantic>=2.7",
# "pydantic-settings>=2",
# "sqlalchemy[asyncio]>=2.0",
# "asyncpg>=0.29",
# "alembic>=1.13",
# "structlog>=24",
# "python-dotenv>=1",
# "sse-starlette>=3.0.2",
# "httpx>=0.27",
# "orjson>=3",
# "langgraph>=0.2",
# "langchain>=0.2",
# "langgraph-checkpoint-sqlite>=1.0", # local/dev
# "langgraph-checkpoint-postgres>=1.0", # prod persistence
# "psycopg[binary]>=3.2", # for Postgres checkpointer
# ]